# Generated by Django 3.2.7 on 2021-10-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(default='shop/book/author/author.png', upload_to='shop/book/author/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='shop/book/book.png', upload_to='shop/book/'),
        ),
    ]
